### ISSUE TITLE
Change variable name from Total_Salary to totalSalary

### ISSUE THREAD

**Issue by KrishnakanthYachareni** [SravanthiYachareni/c-programming#5]
https://github.com/SravanthiYachareni/c-programming/blob/59ed42cb0efa1a6fd22f1d978746b2f79ceb6d2c/ConditionalStatementeAssignments/SalaryofMedical.c#L6

**Comment by SravanthiYachareni** [comment]
This program modified

**Comment by SravanthiYachareni** [comment]
MedicalSalary modified

**Comment by SravanthiYachareni** [comment]
modified

**Comment by SravanthiYachareni** [comment]
MedicalSalary modified
